env:
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 13
  sourceType: module
rules: {
  "no-console": "off",
  "no-restricted-syntax": [
    "error",
    {
      "selector": "CallExpression[callee.object.name='console'][callee.property.name!=/^(log|warn|error|info|trace)$/]",
      "message": "Unexpected property on console object was called"
    }
  ],
  "import/extensions": "off"
}
